databases:
  - name: gestion-boisson-db
    databaseName: gestion_boisson
    user: postgres
    plan: free

services:
  - type: web
    name: gestion-boisson-backend
    runtime: docker
    plan: free
    branch: deploy
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gestion-boisson-db
          property: connectionString
      - key: PORT
        value: 8080
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"
    autoDeploy: true
    buildFilter:
      paths:
        - src/**
        - pom.xml
        - Dockerfile
    startCommand: "catalina.sh run"